# -*- coding: utf-8 -*-
"""Prova_Unidade1_Pedro_Vitor_Freitas.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F41MWevUbMMZ8m0gk3HRpsAGPxirSFty
"""

#3
def receberHora():
    h = int(input('Horas: '))
    m = int(input('Minutos: '))
    return [h, m]

def converterPara12(hora):
    h = hora[0]
    m = hora[1]
    if h == 0:
        return f'{h}:{m} A'
    elif h == 12:
        return f'{h}:{m} P'
    elif h > 12:
        h -= 12
        return f'{h}:{m} P'
    else:
        return f'{h}:{m} A'
converterPara12(receberHora())

#4
vendas = {'Pedro':50, 'Maria':30, 'Jose':60, 'Carlos':38}
def gerarRelatorio(vendas):
  total = 0
  maiorVenda = 0    
  for k, v in vendas.items():
    total += v
    if v > maiorVenda:
      maiorVenda = v
    with open('/content/drive/MyDrive/arquivo.txt', 'a') as arquivo:
      arquivo.write(f'{k}: {v}\n')
  with open('/content/drive/MyDrive/arquivo.txt', 'a') as arquivo:
    arquivo.write(f'\nTotal de vendas: {total}\nMaior venda: {maiorVenda}')
  return arquivo
gerarRelatorio(vendas)